### Video upload
POST http://localhost:8080/videos/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="video.mp4"
Content-Type: video/mp4

< C:\path\to\file\video.mp4
--WebAppBoundary
Content-Disposition: form-data; name="name"

Video name
--WebAppBoundary--

### Get videos list (10 newest videos)
GET http://localhost:8080/videos

### Get videos list with custom limit
GET http://localhost:8080/videos?limit=20

### Get videos list with cursor
GET http://localhost:8080/videos?lastVideoId=<id>

### Get videos list with cursor and limit
GET http://localhost:8080/videos?limit=20&lastVideoId=<id>

### Search video by name (chainable with limit and lastVideoId parameters)
GET http://localhost:8080/videos?search=<name>

### Get video metadata
GET http://localhost:8080/videos/<id>

### Delete video
DELETE http://localhost:8080/videos/<id>

### Bulk delete videos
DELETE http://localhost:8080/videos/bulk
Content-Type: application/json

[
    "<id1>",
    "<id2>"
]

### Get video thumbnail
GET http://localhost:8080/videos/<id>/thumbnail

### Get video manifest
GET http://localhost:8080/videos/<id>/manifest.m3u8

### Get video chunk (index1.ts, index2.ts,...)
GET http://localhost:8080/videos/<id>/index1.ts
Range: bytes=0-
