### Video upload
POST http://localhost:8080/videos/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="video.mp4"
Content-Type: video/mp4

< C:\path\to\file\video.mp4
--WebAppBoundary--

### Get videos list (10 newest videos)
GET http://localhost:8080/videos

### Get videos list with custom limit
GET http://localhost:8080/videos?limit=20

### Get videos list with cursor
GET http://localhost:8080/videos?lastVideoid=<id>

### Get videos list with cursor and limit
GET http://localhost:8080/videos?limit=20&lastVideoid=<id>

### Get video metadata
GET http://localhost:8080/videos/<id>

### Delete video
DELETE http://localhost:8080/videos/<id>

### Get video thumbnail
GET http://localhost:8080/videos/<id>/thumbnail

### Get video manifest
GET http://localhost:8080/videos/<id>/manifest.m3u8

### Get video chunk (index1.ts, index2.ts,...)
GET http://localhost:8080/videos/<id>/index1.ts
Range: bytes=0-
